# Generated by Django 4.2.7 on 2023-11-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsmodel',
            name='description',
            field=models.TextField(default='No description available'),
        ),
    ]
