# Generated by Django 5.0.6 on 2024-07-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sites', '0002_alter_post_wall_fanpage_post_fanpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fanpage',
            name='title',
        ),
        migrations.AddField(
            model_name='fanpage',
            name='fanpage_name',
            field=models.CharField(default='default_fanpage', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
