# Generated by Django 5.0.6 on 2024-07-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sites', '0004_lastvisited'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanpage',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userwall',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
