# Generated by Django 5.0.6 on 2024-07-17 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sites', '0006_friendship_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='last_message',
            new_name='last_action',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='user2',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='user1',
            new_name='sender',
        ),
        migrations.AddField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('sender', 'receiver')},
        ),
    ]
